### ISSUE TITLE
Failed to parse block

### ISSUE THREAD

**Issue by citizenz7** [dvandal/cryptonote-nodejs-pool#115]
Trying to run a new pool. Got this error each tile i try to connect with my miner app (xmrig-cpu) :

Error: Failed to parse block
    at Error (native)
    at Object.BlockTemplate.nextBlob (/home/mumbly/KEPL/pool/lib/pool.js:156:29)
    at Object.Miner.getJob (/home/mumbly/KEPL/pool/lib/pool.js:335:41)
    at handleMinerMethod (/home/mumbly/KEPL/pool/lib/pool.js:476:28)
    at handleMessage (/home/mumbly/KEPL/pool/lib/pool.js:840:13)
    at Socket.<anonymous> (/home/mumbly/KEPL/pool/lib/pool.js:894:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by citizenz7** [comment]
For KEPL coin :
    "cnAlgorithm": "cryptonight",
    "cnVariant": 1,
    "cnBlobType": 2,

... and tit's working fine now !
