### ISSUE TITLE
One pool works... Other not..

### ISSUE THREAD

**Issue by swanseahost** [dvandal/cryptonote-nodejs-pool#123]
Hi there,

I have installed 2 ubuntu servers.  Set them up identical (apart from hostname and IP of course)

One works fine and the other gives me this error

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/home/miner/pool/lib/utils.js:27:100)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/miner/pool/lib/notifications.js:16:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

How to fix please ?

Thanks

**Comment by dvandal** [comment]
:)
