### ISSUE TITLE
I installed the readme, but there was an error.

### ISSUE THREAD

**Issue by imofei** [dvandal/cryptonote-nodejs-pool#142]
root@VM-0-231-ubuntu:/usr/local/pool# npm update

> cryptoforknote-util@1.0.0 install /usr/local/pool/node_modules/cryptoforknote-util
> node-gyp rebuild

make: Entering directory '/usr/local/pool/node_modules/cryptoforknote-util/build'
  CXX(target) Release/obj.target/cryptoforknote/src/main.o

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
cryptoforknote.target.mk:111: recipe for target 'Release/obj.target/cryptoforknote/src/main.o' failed
make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 4
make: Leaving directory '/usr/local/pool/node_modules/cryptoforknote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-91-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/pool/node_modules/cryptoforknote-util
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptoforknote-util@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-20T07_53_14_039Z-debug.log

**Comment by bruceleeon** [comment]
Do you have aes? grep -o aes /proc/cpuinfo

**Comment by adi3yz** [comment]
same happen to me.. this error after i update git.. before this it run ok

**Comment by WaReZoR-UA** [comment]
same problem. i use 16.04.4 LTS (GNU/Linux 4.4.0-127-generic i686). When i build in x64 system, everithing ok

**Comment by WaReZoR-UA** [comment]
```
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-127-generic i686)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Могут быть обновлены 4 пакета.
2 обновления касаются безопасности системы.


Last login: Sat May 26 15:57:53 2018 from 185.189.112.97
loki@ubuntu:~$ cd pool
loki@ubuntu:~/pool$ npm update
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated buildmail@4.0.1: This project is unmaintained

> cryptoforknote-util@1.0.0 install /home/loki/pool/node_modules/cryptoforknote-util
> node-gyp rebuild

make: вход в каталог «/home/loki/pool/node_modules/cryptoforknote-util/build»
  CXX(target) Release/obj.target/cryptoforknote/src/main.o
In file included from ../src/main.cc:1:0:
/usr/include/c++/5/cmath:41:28: fatal error: bits/c++config.h: Нет такого файла или каталога
compilation terminated.
cryptoforknote.target.mk:109: ошибка выполнения рецепта для цели «Release/obj.target/cryptoforknote/src/main.o»
make: *** [Release/obj.target/cryptoforknote/src/main.o] Ошибка 1
make: выход из каталога «/home/loki/pool/node_modules/cryptoforknote-util/build»
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-127-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/loki/pool/node_modules/cryptoforknote-util
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN cryptonote-nodejs-pool@1.3.4 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptoforknote-util@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/loki/.npm/_logs/2018-05-26T12_58_35_005Z-debug.log
```

**Comment by luaus** [comment]
yup tried on ubuntu 14.04, 16.04, and 18.04.  
`~/pool$ npm update
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> cryptoforknote-util@1.0.0 install /home/admin/pool/node_modules/cryptoforknote-util
> node-gyp rebuild

make: Entering directory `/home/admin/pool/node_modules/cryptoforknote-util/build'
  CXX(target) Release/obj.target/cryptoforknote/src/main.o
make: g++: Command not found
make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 127
make: Leaving directory `/home/admin/pool/node_modules/cryptoforknote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin/pool/node_modules/cryptoforknote-util
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptoforknote-util@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2018-05-29T00_54_18_966Z-debug.log
admin@server1:~/pool$ 
`

**Comment by waterfallm** [comment]
And the Fix was?
