### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by citizenz7** [dvandal/cryptonote-nodejs-pool#166]
I try to install a new pool but it fails installing . I have 2 more pools with the same config that works just fine on the same server... : 

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-127-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/mumbly/LINES/pool/node_modules/cryptonight-hashing
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Linux 4.4.0-127-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! cryptonight-hashing@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonight-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonight-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonight-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mumbly/LINES/pool/npm-debug.log

**Comment by WaReZoR-UA** [comment]
https://github.com/dvandal/cryptonote-nodejs-pool/issues/165

**Comment by dvandal** [comment]
MoneroOcean had an issue when building cryptonight-hashing on Ubuntu and they fixed ~15 minutes ago. Please reinstall node modules / npm update.

**Comment by WaReZoR-UA** [comment]
tnks!
