### ISSUE TITLE
/report and /notify telegrambot not working

### ISSUE THREAD

**Issue by adi3yz** [dvandal/cryptonote-nodejs-pool#171]
can u check that

**Comment by dlegend116** [comment]
same with me, after update with out changing info in telegram except for adding /report /blocks etc Stats stop being sent idk what is wrong

**Comment by citizenz7** [comment]
same here with errors : 

**telegram_crash.log** and **telegramBot_crash.log** :
2018-05-30 21:01:16
TypeError: Cannot read property 'username' of undefined
    at sendPoolStats (/home/mumbly/IRIDIUM/pool/lib/telegramBot.js:105:86)
    at null._repeat (/home/mumbly/IRIDIUM/pool/lib/telegramBot.js:73:29)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**master_error.log :** 
2018-05-30 21:01:16 telegramBot died, spawning replacement...

**Comment by dvandal** [comment]
Issue with `TypeError: Cannot read property 'username' of undefined` when using periodical statistics has been already fixed. Please update and let me know.

**Comment by dlegend116** [comment]
I updated again after latest commit and it is Working now for me thanks @dvandal
