### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by bytecanarias** [dvandal/cryptonote-nodejs-pool#186]
Hi, I have installed
node -v 8.0 npm -v 6.1.0 he did npm update as 5 or 6 times and so I still get this error

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/home/bytecanarias/pool/lib/utils.js:27:100)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bytecanarias/pool/lib/notifications.js:16:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

**Comment by userid2018** [comment]
I just did a clean install following line by line and getting the same error.

Any Help is appreciated

**Comment by happysmash27** [comment]
In which way did you update it? Mine still doesn't work.

**Comment by bytecanarias** [comment]
Why crypto? I recommend the Telegram group https://t.me/CryptonotePool
