### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by dnbinc** [dvandal/cryptonote-nodejs-pool#19]

**Comment by dnbinc** [comment]
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/masari/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

I am not sure what to correct.. any ideas?

**Comment by Haafingar** [comment]
What was the solution to this?

**Comment by dnbinc** [comment]
Was a mistake.
