### ISSUE TITLE
Error: Symbol cryptonight_hashing_module not found.

### ISSUE THREAD

**Issue by katanaks** [dvandal/cryptonote-nodejs-pool#22]
2018-04-13 16:15:46 [master] Pool fork 4 died, spawning replacement worker...
Error: Symbol cryptonight_hashing_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/pools/xtl/node_modules/cryptonight-hashing/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/pools/xtl/node_modules/cryptonight-hashing/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by dvandal** [comment]
Hi,

We where not using cryptonight-hashing previously but since yesterday we switched to this to properly support Monero v7 / Cryptonight v1 algorithm. Please upgrade pool software to lastest version.
