### ISSUE TITLE
last update incorrect?

### ISSUE THREAD

**Issue by Cideg** [dvandal/cryptonote-nodejs-pool#229]
Hello after the last update today, the following error message appears.

How can this be fixed?

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/workpool/init.js:29:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
2018-06-21 14:34:07 [master] Pool fork 2 died, spawning replacement worker...
/root/workpool/lib/pool.js:721
            let age = parseFloat(replies[0][1])
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/workpool/init.js:29:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
2018-06-21 14:34:07 [master] Pool fork 1 died, spawning replacement worker...

**Comment by HKoody** [comment]
Update Node.js + npm to last version. Run npm -v if you want to make sure npm updated correctly. After update you can tell nvm which version to use in each new shell with nvm use #.#.# and set a default with alias: nvm alias default node. Set "use" and "default" to last version.
Remove the dependencies by deleting the node_modules directory with rm -r node_modules.
Run npm update to force updating/reinstalling of the dependencies. After update run npm outdated, it will check every module defined in package.json and see if there is a newer version in the NPM registry.

**Comment by Cideg** [comment]
No it is not because the error must be somewhere else.
I assume that some signs were forgotten: "or cling


And for your approach: Otherwise, it is sufficient for this Poll art from nvm directly to use
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash
 sudo apt-get install -y nodejs
alternative
curl https://raw.githubusercontent.com/creationix/nvm/v0.33.9/install.sh | bash
nvm install 4.8
nvm use 4.8
nvm alias default 4.8
nvm use default
