### ISSUE TITLE
Pool forks... died. Nodejs problem ???

### ISSUE THREAD

**Issue by citizenz7** [dvandal/cryptonote-nodejs-pool#237]
2018-06-25 14:24:32 [master] Pool fork 1 died, spawning replacement worker...
/home/mumbly/CATALYST/pool/lib/pool.js:721
            let age = parseFloat(replies[0][1])
            ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mumbly/CATALYST/pool/init.js:29:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Is this related to nodejs version ?
My nodejs version : nodejs -v
v4.2.6

All former versions of cryptonote-nodejs-pool are working with my other pools.
I use Ubuntu 16.04

Should i update now with
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash
 sudo apt-get install -y nodejs

If i update : will it be safe for my other pools ?

THANX !

**Comment by jagerman** [comment]
My mistake; `let` apparently isn't supported in node 4.  Changing the `let` to `var` on that line (lib/pool.js line 721) should fix it.  I'll submit a PR to fix it as well.

**Comment by citizenz7** [comment]
Just to let you know, i've made (in the pool root directory) :
$ rm -rf node_modules
$ npm update
$ sudo -s
# npm outdated
and it just ... worked :)
I got several warning about some modules that could not be fixed... but it worked anyway.
