### ISSUE TITLE
TelegramBot.js Crash - Cannot read property 'hashrate' of undefined

### ISSUE THREAD

**Issue by nilhcraiv** [dvandal/cryptonote-nodejs-pool#263]
Hello,

The bot has been working correctly during several days but since a few hours ago I have this log in the telegramBot_crash.log file. Is it a known problem? Right now the bot does not respond because of it. This message in the log file occurs every second, in a loop.

_(I think it happens when someone registers an address in the bot that does not exist in the pool, but I'm not sure.)_

Thanks!

```
2018-07-03 10:08:46
TypeError: Cannot read property 'hashrate' of undefined
    at /home/user/folder/cryptonote-nodejs-pool/lib/telegramBot.js:184:66
    at IncomingMessage.<anonymous> (/home/user/folder/cryptonote-nodejs-pool/lib/apiInterfaces.js:64:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by nilhcraiv** [comment]
Hello,

This code solve the problem to me:

```
if(typeof data.stats === 'undefined')
        {
                var temporal = { hashrate: 0, balance: 0, paid: 0, lastShare: 0};
                data.stats = temporal;
        }   
```

in sendMinerStats function:

```
function sendMinerStats(telegramMsg, address) {
    log('info', logSystem, 'Miner report request from @%s (%s) for address: %s', [telegramMsg.from.username, telegramMsg.from.id, address]);
    apiInterfaces.pool('/stats_address?address='+address, function(error, data) {
        if (error || !data) {
            log('error', logSystem, 'Unable to get API data for miner stats: ' + error);
            return bot.sendMessage(id, 'Unable to get miner statistics. Please retry.');
        }
        if(typeof data.stats === 'undefined')
        {
                var temporal = { hashrate: 0, balance: 0, paid: 0, lastShare: 0};
                data.stats = temporal;
        }      

        var minerHashrate = utils.getReadableHashRate(data.stats.hashrate);
        var minerBalance = utils.getReadableCoins(data.stats.balance);
        var minerPaid = utils.getReadableCoins(data.stats.paid);
        var minerLastShare = timeAgo.ago(new Date(parseInt(data.stats.lastShare * 1000)));

        var response = '*Report for ' + address.substring(0,7)+'...'+address.substring(address.length-7) + '*\n';
        response += 'Hashrate: ' + minerHashrate + '\n';
        response += 'Last share: ' + minerLastShare + '\n';
        response += 'Balance: ' + minerBalance + '\n';
        response += 'Paid: ' + minerPaid + '\n';
        if (data.workers && data.workers.length > 0) {
            var f = true;
            for (var i in data.workers) {
                if (!data.workers[i] || !data.workers[i].hashrate || data.workers[i].hashrate === 0) continue;
                if (f) {
                    response += '\n';
                    response += '*Active Workers*\n';
                }
                var workerName = data.workers[i].name;
                var workerHashrate = utils.getReadableHashRate(data.workers[i].hashrate);
                response += workerName + ': ' + workerHashrate + '\n';
                f = false;
            }
        }
        bot.sendMessage(telegramMsg.from.id, response, { parse_mode: 'Markdown' });

        var apiRequest = '/set_telegram_notifications?chatId='+telegramMsg.from.id+'&type=default&address='+address;
        apiInterfaces.pool(apiRequest, function(error, response) {});
    });
}
```
