### ISSUE TITLE
notifications.js

### ISSUE THREAD

**Issue by WaReZoR-UA** [dvandal/cryptonote-nodejs-pool#268]
2018-07-05 16:36:39 [master] Starting Cryptonote Node.JS pool version v1.3.5
2018-07-05 16:36:39 [master] Pool spawned on 3 thread(s)
2018-07-05 16:36:39 [chartsDataCollector] Started

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/home/coin/pool/lib/utils.js:27:100)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/coin/pool/lib/notifications.js:16:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by bruceleeon** [comment]
double check your config... paste it here if you like. I have that happen usually when there is an error in my config

**Comment by WaReZoR-UA** [comment]
config is correct. perhaps the coin isn't supported.
