### ISSUE TITLE
Eval error

### ISSUE THREAD

**Issue by west-pool** [dvandal/cryptonote-nodejs-pool#271]
Hi,

anyone have this issue?

pool/lib/pool.js:674
        updateScore = ['eval', `
                               ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/luissilva/pool/init.js:29:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by muscleman** [comment]
nope
