### ISSUE TITLE
24 Block Chart

### ISSUE THREAD

**Issue by SixLitr** [dvandal/cryptonote-nodejs-pool#303]
I am getting an error when trying to enable the 24hr block chart. Currently it's set to hidden in the pool_blocks.html and enabling it shows the black space for it, however when I enable the following it throws api errors and stopped showing the list of pool blocks found below.

(Found at the bottom of the config.json)

`"blocks": {
        "enabled": true,
        "days": 30
    }
}`

How exactly do we enable the 24 pool blocks chart and what is causing the api error? I've left the above snippet set to false for the time being and everything runs as usual.

**Comment by OptimusBlue** [comment]
I am experiencing a similar issue, the Blocks Found chart does not want to show even when it is enabled.

**Comment by OptimusBlue** [comment]
I was able to resolve the issue on my side, some previous update I missed where the javascript need to be changed in pool_blocks.html

 
<script>
// Hide blocks chart on load
$('#blocksChart').hide();
to 

<script>
// Hide blocks chart on load
$('#blocksChart').show();

**Comment by SixLitr** [comment]
I had already been able to switch from hide to show on the blocksChart, but my problem is my pool_blocks page wont show any blocks when I do, or rather when I enable:

`"blocks": {
            "enabled": true,
            "days": 30
        }` 
in my config.json all my blocks disappear, so I have to switch it to false. Additionally, if I hit Load More to try and see them I get this error in the api.js windows:
`
TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at /home/bflokiwest/pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/home/bflokiwest/pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/home/bflokiwest/pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/home/bflokiwest/pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/home/bflokiwest/pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/home/bflokiwest/pool/node_modules/redis/index.js:274:27)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
`
