### ISSUE TITLE
API Error: "string" must be a string, Buffer, or ArrayBuffer

### ISSUE THREAD

**Issue by tetyanamyr** [dvandal/cryptonote-nodejs-pool#308]
**Coin:** **_Electroneum_** 
**Pool:**
- Node version: v8.11.3
- Redis server v=4.0.10
- Config attached below 

**Issue description:**  Pool has 1 miner and two workers (2 ASICS), 3 blocks were found on ASIC statistic which is accurate, but none of them went to "block candidates in Redis" and Found Blocks in pool remain 0.

I checked api_crash.log file and there were 3 identical messages with different timestamp:

All used variables already wrapped by JSON.stringify... 

_Please any advice will be appreciated._

```
2018-07-23 02:29:51
TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at /home/pyruss/pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/home/pyruss/pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/home/pyruss/pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/home/pyruss/pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/home/pyruss/pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/home/pyruss/pool/node_modules/redis/index.js:274:27)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**Comment by muscleman** [comment]
prolly not got the right daemon port
