### ISSUE TITLE
press "load more" error

### ISSUE THREAD

**Issue by earthGavinLee** [dvandal/cryptonote-nodejs-pool#343]
![2018-08-28 14-57-58](https://user-images.githubusercontent.com/8288083/44706443-29732200-aad4-11e8-9bb8-a07722160bcd.jpg)

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:516:11)
    at /mnt/Pool/cryptonote-nodejs-pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:516:11)
    at /mnt/Pool/cryptonote-nodejs-pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:516:11)
    at /mnt/Pool/cryptonote-nodejs-pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:516:11)
    at /mnt/Pool/cryptonote-nodejs-pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:516:11)
    at /mnt/Pool/cryptonote-nodejs-pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:516:11)
    at /mnt/Pool/cryptonote-nodejs-pool/lib/api.js:860:38
    at Object.callbackOrEmit [as callback_or_emit] (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/mnt/Pool/cryptonote-nodejs-pool/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)

2018-08-28 14:40:22 [master] API died, spawning replacement...
(node:28688) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by DarkMoonCBK** [comment]
me too............
