### ISSUE TITLE
slushMining is undefined?

### ISSUE THREAD

**Issue by Methodiseme** [dvandal/cryptonote-nodejs-pool#357]
node init.js 
2018-09-13 18:28:14 [master] Starting Cryptonote Node.JS pool version v1.3.5
2018-09-13 18:28:16 [master] Pool spawned on 4 thread(s)
2018-09-13 18:28:21 [chartsDataCollector] Started
2018-09-13 18:28:22 [unlocker] Started
2018-09-13 18:28:22 [payments] Started

````
TypeError: Cannot read property 'enabled' of undefined
    at config (/var/www/pool2/lib/api.js:340:67)
    at /var/www/pool2/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/var/www/pool2/node_modules/async/lib/async.js:233:13)
    at _parallel (/var/www/pool2/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/var/www/pool2/node_modules/async/lib/async.js:731:9)
    at collectStats (/var/www/pool2/lib/api.js:208:11)
    at Object.<anonymous> (/var/www/pool2/lib/api.js:1787:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
````

slushMiningEnabled: config.poolServer.slushMining.enabled,

                                    ^
                                    slushMining is undefined?

**Comment by muscleman** [comment]
prolly missing a comma or the field in the config. see readme or other config as baseline
