### ISSUE TITLE
Payment processor died, spawning replacement

### ISSUE THREAD

**Issue by Akimardb** [dvandal/cryptonote-nodejs-pool#364]
Hi all. Random issue that's just cropped up. Pool has been running fine for weeks now and all of a sudden my payment processor has died and will not start back up.

I get two sets of errors - first is:

`2018-09-29 16:27:26 Payment processor died, spawning replacement...`

The second is:

`2018-09-29 16:28:17
TypeError: cnUtil.address_decode_integrated is not a function
    at getAddressPrefix (/home/richard/pool/lib/utils.js:38:32)
    at Object.exports.isIntegratedAddress (/home/richard/pool/lib/utils.js:56:25)
    at /home/richard/pool/lib/paymentProcessor.js:144:49
    at fn (/home/richard/pool/node_modules/async/lib/async.js:746:34)
    at /home/richard/pool/node_modules/async/lib/async.js:1213:16
    at /home/richard/pool/node_modules/async/lib/async.js:166:37
    at /home/richard/pool/node_modules/async/lib/async.js:706:43
    at /home/richard/pool/node_modules/async/lib/async.js:167:37
    at /home/richard/pool/node_modules/async/lib/async.js:1209:30
    at Multi.callback (/home/richard/pool/lib/paymentProcessor.js:98:17)
    at multi_callback (/home/richard/pool/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/home/richard/pool/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/home/richard/pool/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/home/richard/pool/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/home/richard/pool/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/richard/pool/node_modules/redis-parser/lib/parser.js:574:12)`

I can't work out what is causing the issue. The pool has been running fine for weeks - it's processed thousands of transactions. Randomly this morning it just stops and will no longer start back up.

I've resync'd my blockchain, replaced the blockchain daemon, replaced the blockchain wallet RPC, cleared mode_modules and rebuilt, but nothing seems to work anymore.

Any suggestions? I've got payments which are building up.

**Comment by muscleman** [comment]
look in cryptonight.h for you coin on github. try and find the integrated address payment id. it's most likely in hex so convert to integer and put this in the config.json just below your wallet address.

**Comment by muscleman** [comment]
also somebody may have put some funky characters in the paymentid and it messes with redis.
