### ISSUE TITLE
Loader error

### ISSUE THREAD

**Issue by nutsplus** [dvandal/cryptonote-nodejs-pool#37]
internal/modules/cjs/loader.js:683
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

**Comment by dvandal** [comment]
I never seen anyting about a "cjs" module, are you using custom package.json configuration? Which version of node.js is installed?

**Comment by nutsplus** [comment]
If I run node init.js - error binding
/home/nuts/pool/node_modules/cryptonight-hashing/node_modules/bindings/bindings.js:88
        throw e
              ^
Error: Symbol cryptonight_hashing_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/nuts/pool/node_modules/cryptonight-hashing/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/nuts/pool/node_modules/cryptonight-hashing/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)


if I run sudo node.js - 
internal/modules/cjs/loader.js:683
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/nuts/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)

Version of node.js - v0.10.48
NPM version - 2.15.1

I use sumokoin.json configuration - wget https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/config_examples/sumokoin.json

**Comment by dvandal** [comment]
The pool software require Node.JS version 4.x or 8.x and is incompatible with node.js 0.10.48
