### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by WaReZoR-UA** [dvandal/cryptonote-nodejs-pool#382]
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at /home/test/pool/lib/pool.js:202:22
    at /home/test/pool/lib/apiInterfaces.js:69:13
    at ClientRequest.<anonymous> (/home/test/pool/lib/apiInterfaces.js:51:9)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at /home/test/pool/lib/pool.js:202:22
    at /home/test/pool/lib/apiInterfaces.js:69:13
    at ClientRequest.<anonymous> (/home/test/pool/lib/apiInterfaces.js:51:9)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketCloseListener (_http_client.js:363:9)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)

coin bloc used simplewallet.

**Comment by jaysinism** [comment]
I am also having this same exact issue with OMB
Any insight on this error?

**Comment by WaReZoR-UA** [comment]
fixed with change cnBlob
