### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined when using QRL address

### ISSUE THREAD

**Issue by happysmash27** [dvandal/cryptonote-nodejs-pool#383]
Hello! I am trying to upgrade many aspects of my QRL pool, including the backend, which I am looking at replacing with this one. At the moment, I get the following error: 

```
TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/home/minilaroqrl/cryptonote-nodejs-pool/lib/utils.js:27:100)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/minilaroqrl/cryptonote-nodejs-pool/lib/notifications.js:16:13)
    at Module._compile (module.js:652:30)

```

My `"poolAddress"` is set as: 
`"poolAddress": "Q0106004b6f0a3ceeab20b340836e418f60a33f49d5235f74b1effda410f5fe4fd4dbd6cb667c37",`

Looking at the code, it looks like some weird address prefix decoder. Is there any way I can make this pool software work with QRL? My `"initAddressPrefix"` is `null`, as I could not find the file `src/cryptonote_config` in either this codebase, the QRL codebase, or the Qryptonight codebase and this was the value on some of the example configs. QRL uses Cryptonight_v7 in xmr-stak, and the codebase of Qryptonight appears to rely on the code of xmr-stak.

**Comment by happysmash27** [comment]
Changing `"cnBlobType"` from `0` to `1` does not fix this issue. The reason I tried this is that another pool appeared to be using some kind of Forknote pool software.

**Comment by happysmash27** [comment]
Address of the repo my pool is currently running on: https://github.com/theQRL/node-cryptonote-pool. Please note that my Qaddress with the Q in it runs fine there.

**Comment by happysmash27** [comment]
Also, the default address shown isn't even a QRL address.

**Comment by happysmash27** [comment]
QRL addresses, by the way, have prefixes indicating hash type and tree size which look something like`Q010600`, `Q010900`, `Q010400`, etc.

**Comment by happysmash27** [comment]
Why was this issue closed?
