### ISSUE TITLE
Making a Config for my new coin but get Redis error

### ISSUE THREAD

**Issue by Franzferdinan51** [dvandal/cryptonote-nodejs-pool#390]
so just little confusion im trying to make a config for my coin i forked from TRTL and trying to create the config file and keep running into an error on redis this is the error and ive attached the config
[GrubMine.txt](https://github.com/dvandal/cryptonote-nodejs-pool/files/2551230/GrubMine.txt)
[GrubMine.txt](https://github.com/dvandal/cryptonote-nodejs-pool/files/2551231/GrubMine.txt)

root@ubuntu:~/Grub-Pool# node init.js -config=GrubMine.json
2018-11-06 01:00:23 [master] Starting Cryptonote Node.JS pool version v1.3.5

Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

**Comment by Franzferdinan51** [comment]
forgot to mention its a TRTL coin fork

**Comment by muscleman** [comment]
base on trtl config
