### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by thomsonimjd** [dvandal/cryptonote-nodejs-pool#392]
```
TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/home/minerpool/pool/lib/utils.js:27:100)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/minerpool/pool/lib/notifications.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

2018-11-09 09:21:59 [master] API died, spawning replacement...
```

**Comment by paulbrasted** [comment]
I got this error when running the node when it did not manage to connect to the daemon correctly.
I either had an invalid wallet address , wrong algo, wrong port, or server just was not running

**Comment by muscleman** [comment]
prolly using the wrong port to communicate with the daemon
