### ISSUE TITLE
 chartsDataCollector died, spawning replacement

### ISSUE THREAD

**Issue by x23a1s** [dvandal/cryptonote-nodejs-pool#430]
hey there,

i get always this error, pool works great but all few minutes i get this error with chartsDataCollector died, spawning replacement

TypeError: Cannot read property 'maximumPeriod' of undefined
    at /root/pools/hosppool/lib/charts.js:103:47
    at Command.callback (/root/pools/hosppool/lib/charts.js:140:9)
    at normal_reply (/root/pools/hosppool/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/root/pools/hosppool/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/root/pools/hosppool/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/root/pools/hosppool/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/root/pools/hosppool/node_modules/redis/index.js:274:27)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

**Comment by muscleman** [comment]
upgrade to nodejs 10

**Comment by x23a1s** [comment]
thanks that worked

**Comment by infoelektron** [comment]
The same error with nodejs 10 and 11 too...

**Comment by sanich-rd** [comment]
clean redis
