### ISSUE TITLE
Something's wrong.

### ISSUE THREAD

**Issue by lomax1981** [dvandal/cryptonote-nodejs-pool#433]
Drew attention to the fact that periodically there is a bug. Tell me what's wrong?
(node:16465) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at /opt/new_pool/pool/lib/api.js:1695:36
    at request.then.catch.error (/opt/new_pool/pool/lib/apiInterfaces.js:98:21)
    at tryCatcher (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/opt/new_pool/pool/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
(node:16465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
![photo_2019-02-13_18-50-13](https://user-images.githubusercontent.com/23190588/52720001-3d4a0c00-2fc0-11e9-9e06-de92f6dee74e.jpg)

**Comment by muscleman** [comment]
i believe this is related to calling an authorized endpoint, i usually put the network ip in the bindip section of the pool in config.json

**Comment by lomax1981** [comment]
I FIX!! monero-wallet-rpc not connect to daemon.
