### ISSUE TITLE
Promise.js error messages

### ISSUE THREAD

**Issue by synergyits** [dvandal/cryptonote-nodejs-pool#435]
Hi there,

I was hoping you could identify a solution for this issue.

About every 20s this error comes up in the console.
I have seen your issue log #433 that was closed and I have made the change to bindip but I'm still getting this. Also just updated to 1.4.0 - same.

Any help greatly appreciated.

#1 

(node:7389) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at /opt/pool/cryptonote-nodejs-pool/lib/api.js:1695:36
    at request.then.catch.error (/opt/pool/cryptonote-nodejs-pool/lib/apiInterfaces.js:98:21)
    at tryCatcher (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)
(node:7389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)

#2
not as frequent as #1 but it is odd because the telegram bot is working.
I can /stats or /notify just fine.

Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
    at request.then.resp (/opt/pool/cryptonote-nodejs-pool/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/pool/cryptonote-nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)

**Comment by muscleman** [comment]
apiInterfaces has been reverted
