### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by Sberex** [dvandal/cryptonote-nodejs-pool#440]
Plese help, I'm using Dero.

2019-02-25 15:27:35
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/pool/lib/pool.js:128:23)
    at Object.Miner.getJob (/pool/lib/pool.js:302:41)
    at handleMinerMethod (/pool/lib/pool.js:531:28)
    at handleMessage (/pool/lib/pool.js:660:13)
    at Socket.socket.on.on.on.pushMessage (/pool/lib/pool.js:714:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

Package.json:
    "dependencies": {
        "bignum": "0.12.5",
        "async": "1.5.2",
        "redis": "0.12.1",
        "cli-color": "1.1.0",
        "dateformat": "1.0.12",
        "base58-native": "0.1.4",
        "multi-hashing": "git://github.com/zone117x/node-multi-hashing.git",
        "cryptonote-util": "git://github.com/Snipa22/node-cryptonote-util#xmr-Nan-2.0"
    },

**Comment by lomax1981** [comment]
I also have this error on XHV

**Comment by muscleman** [comment]
XHV is prolly the wrong algo

**Comment by lomax1981** [comment]
"cnAlgorithm": "cryptonight_heavy",

**Comment by muscleman** [comment]
cnblobType =?
cnVariant = ?

**Comment by lomax1981** [comment]
"cnVariant": null,
    "cnBlobType": 0,
default /config_examples

**Comment by lomax1981** [comment]
2019-02-28 11:03:54 (Thread 1) Error submitting block at height 275576 from hvxxvFELEFS9wCj7rYxr4QN6eDSzywF62TQ9eWzKdou1dMBWpfQDNmB8vUCBZoeqgqAuQ7C4d6163HgYrNmeEjwq9KFVCqd8pw@::ffff:192.99.212.240, share type: "trusted" - {"code":-7,"message":"Block not accepted"}

**Comment by muscleman** [comment]
try 1 and 0

**Comment by muscleman** [comment]
this is an issue with the hashing packages
