### ISSUE TITLE
Additional Requirements For Linux Mint: Git, g++ and make

### ISSUE THREAD

**Issue by TunercarZ** [dvandal/cryptonote-nodejs-pool#464]
apt install git

then used Synaptic Package Manager to install:
- g++
- make

Otherwise received errors on command
$ npm update

> cryptoforknote-util@4.1.0 install /home/cryptonight/pool/node_modules/cryptoforknote-util
> node-gyp rebuild
> 
> make: Entering directory '/home/cryptonight/pool/node_modules/cryptoforknote-util/build'
>   CXX(target) Release/obj.target/cryptoforknote/src/main.o
> make: g++: Command not found
> cryptoforknote.target.mk:117: recipe for target 'Release/obj.target/cryptoforknote/src/main.o' failed
> make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 127
> make: Leaving directory '/home/cryptonight/pool/node_modules/cryptoforknote-util/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/nodejs/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Linux 4.15.0-20-generic
> gyp ERR! command "/usr/local/lib/nodejs/node-v10.15.3-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/cryptonight/pool/node_modules/cryptoforknote-util
> gyp ERR! node -v v10.15.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! cryptoforknote-util@4.1.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the cryptoforknote-util@4.1.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/cryptonight/.npm/_logs/2019-04-01T16_00_14_988Z-debug.log
>

**Comment by TunercarZ** [comment]
0 Vulnerabilities
after requirements met 
{Linux 4.15.0-20-generic}
