### ISSUE TITLE
Pool fork 1 died, spawning replacement worker... happens every 10 seconds

### ISSUE THREAD

**Issue by crypthusiast0** [dvandal/cryptonote-nodejs-pool#486]
I have been getting this error here:
```
/home/pool/pool/node_modules/bindings/bindings.js:99
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pool/pool/node_modules/bignum/build/bignum.node
 → /home/pool/pool/node_modules/bignum/build/Debug/bignum.node
 → /home/pool/pool/node_modules/bignum/build/Release/bignum.node
 → /home/pool/pool/node_modules/bignum/out/Debug/bignum.node
 → /home/pool/pool/node_modules/bignum/Debug/bignum.node
 → /home/pool/pool/node_modules/bignum/out/Release/bignum.node
 → /home/pool/pool/node_modules/bignum/Release/bignum.node
 → /home/pool/pool/node_modules/bignum/build/default/bignum.node
 → /home/pool/pool/node_modules/bignum/compiled/8.16.0/linux/x64/bignum.node
    at bindings (/home/pool/pool/node_modules/bindings/bindings.js:96:9)
    at Object.<anonymous> (/home/pool/pool/node_modules/bignum/index.js:1:92)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pool/pool/lib/pool.js:13:14)
2019-06-10 15:47:29 [master] Pool fork 1 died, spawning replacement worker...
```

Why is this happening and what should I do about it?
Thanks

**Comment by Crasha** [comment]
I'm getting the same issue whenever I try and start mining on the pool. However I get this error;

`
2019-06-16 16:29:10 [api] Broadcasting to 1 visitors and 0 address lookups
(node:7405) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

TypeError: buffArray.reverse is not a function
    at Miner.getTargetHex (/home/miningpool/node-cryptonote-pool/lib/pool.js:288:19)
    at Miner.getJob (/home/miningpool/node-cryptonote-pool/lib/pool.js:305:27)
    at handleMinerMethod (/home/miningpool/node-cryptonote-pool/lib/pool.js:514:28)
    at handleMessage (/home/miningpool/node-cryptonote-pool/lib/pool.js:648:13)
    at Socket.<anonymous> (/home/miningpool/node-cryptonote-pool/lib/pool.js:702:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)

2019-06-16 16:29:19 [master] Pool fork 2 died, spawning replacement worker...

`

**Comment by muscleman** [comment]
did you `rm -rf node-modules && npm install`

Plus what version of node you using?

**Comment by muscleman** [comment]
try this version if dvandal won't work.`https://github.com/muscleman/cryptonote-nodejs-pool`

**Comment by muscleman** [comment]
fixed?

**Comment by owenashurst** [comment]
Sorry for not replying, I think I used master or a release, I'll double check on the server when I get a chance.

**Comment by gabcraftia** [comment]
i get the same error 
/home/gabber/pool/node_modules/bindings/bindings.js:99
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/gabber/pool/node_modules/bignum/build/bignum.node
 → /home/gabber/pool/node_modules/bignum/build/Debug/bignum.node
 → /home/gabber/pool/node_modules/bignum/build/Release/bignum.node
 → /home/gabber/pool/node_modules/bignum/out/Debug/bignum.node
 → /home/gabber/pool/node_modules/bignum/Debug/bignum.node
 → /home/gabber/pool/node_modules/bignum/out/Release/bignum.node
 → /home/gabber/pool/node_modules/bignum/Release/bignum.node
 → /home/gabber/pool/node_modules/bignum/build/default/bignum.node
 → /home/gabber/pool/node_modules/bignum/compiled/11.15.0/linux/x64/bignum.node
    at bindings (/home/gabber/pool/node_modules/bindings/bindings.js:96:9)
    at Object.<anonymous> (/home/gabber/pool/node_modules/bignum/index.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/gabber/pool/lib/pool.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
2019-07-17 13:04:34 [master] Pool fork 3 died, spawning replacement worker

**Comment by muscleman** [comment]
looks like npm install is failing to build one of the pool dependencies.

looks like bignum.js

https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/lib/pool.js#L13

so.

what node and npm version?

**Comment by gabcraftia** [comment]
i got it working with some friends.
anyway thanks for the help.

**Comment by owenashurst** [comment]
Please be more specific as to how you got it working as it could help other
people if they run into the same issue - not to mention it'll also help the
devs if there's something wrong with the packages etc.

**Comment by muscleman** [comment]
yes, what was the fix.

**Comment by gabcraftia** [comment]
reinstalled npm and boost
