### ISSUE TITLE
krypton error

### ISSUE THREAD

**Issue by revizor201** [dvandal/cryptonote-nodejs-pool#504]
Failed to read config file krypton.json

SyntaxError: Unexpected token / in JSON at position 850
/home/alisa/pool/lib/logger.js:29
let logDir = config.logging.files.directory;
             ^

ReferenceError: config is not defined
    at Object.<anonymous> (/home/alisa/pool/lib/logger.js:29:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alisa/pool/init.js:17:1)
    at Module._compile (module.js:652:30)

**Comment by muscleman** [comment]
most likely the comments in the json file
