### ISSUE TITLE
 Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Stardock2018** [dvandal/cryptonote-nodejs-pool#512]
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Multi.callback (/home/chrisk/lokipool/lib/pool.js:892:37)
    at multi_callback (/home/chrisk/lokipool/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/home/chrisk/lokipool/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/home/chrisk/lokipool/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/home/chrisk/lokipool/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/home/chrisk/lokipool/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/chrisk/lokipool/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/chrisk/lokipool/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by TheDevMinerTV** [comment]
Same thing here

**Comment by muscleman** [comment]
this still an issue?

**Comment by muscleman** [comment]
Started an xnu pool and didn't see any error logs.
