### ISSUE TITLE
xmr-node-proxy

### ISSUE THREAD

**Issue by rplant8** [dvandal/cryptonote-nodejs-pool#535]
does dvandal-pool support xmr-node-proxy? judging by the commits should, but it does not work.

on pool:
2019-12-03 01:33:51 [pool] (Thread 2) Miner connected 46uGZp...PMMemsYzj@10.10.10.34 on port 7050
2019-12-03 01:33:51 [pool] (Thread 2) ip=10.10.10.34 pass=proxy agent=xmr-node-proxy/0.15.1 remotePort=53384
2019-12-03 01:33:51 [pool] (Thread 2) Worker Name: proxy
2019-12-03 01:33:51 [pool] (Thread 2) Miner difficulty fixed to 20000

on proxy:
The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN
/home/node/xmr-node-proxy/lib/xmr.js:191
        return cnUtil.convert_blob(this.buffer, this.blob_type).toString('hex');
                      ^

Error: Failed to parse block
    at BlockTemplate.nextBlob (/home/node/xmr-node-proxy/lib/xmr.js:191:23)
    at Miner.getJob (/home/node/xmr-node-proxy/lib/xmr.js:235:36)
    at handleMinerData (/home/node/xmr-node-proxy/proxy.js:1120:28)
    at handleMessage (/home/node/xmr-node-proxy/proxy.js:1413:13)
    ...

on supportxmr.com work

pool config:
    "daemonType": "default",
    "cnAlgorithm": "randomx",
    "cnVariant": 0,
    "cnBlobType": 0,
    "includeHeight": false,
    "isRandomX": true,

proxy config:
      "algo": [ "rx/0" ],
      "blob_type": "cryptonote",

ssl off pool/proxy/miner

**Comment by muscleman** [comment]
try pull tonight's fixes and trying again

**Comment by rplant8** [comment]
hash = cryptoNight(convertedBlob, Buffer.from(blockTemplate.seed_hash, 'hex'), cnVariant);
not helped, all so same

**Comment by muscleman** [comment]
Hmm. Well it fixed randomx arqma. Try pulling entire git again

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by muscleman** [comment]
resolved?
