### ISSUE TITLE
TRTL Issue

### ISSUE THREAD

**Issue by delarius** [dvandal/cryptonote-nodejs-pool#59]
Hi,

I want to use your pool for TurtleCoin.
That coin is forked to algo CryptoNight Lite V1.
Is it possible to use it with your software?
At the moment I am using cryptonote-forknote-pool and thats working fine.

With your pool I am getting:

Error: Failed to parse block
    at BlockTemplate.nextBlob (/home/trtlpool/pool/lib/pool.js:171:23)
    at Miner.getJob (/home/trtlpool/pool/lib/pool.js:341:41)
    at handleMinerMethod (/home/trtlpool/pool/lib/pool.js:687:28)
    at handleMessage (/home/trtlpool/pool/lib/pool.js:825:13)
    at Socket.<anonymous> (/home/trtlpool/pool/lib/pool.js:879:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)

**Comment by Chinsusu** [comment]
same to me with ipbc. they have a different algo. Pls wait @dvandal will fix it

**Comment by delarius** [comment]
Yep, thats correct. There is already a patch for the standard forknote pool:
"multi-hashing": "git://github.com/turtlecoin/node-multi-hashing-node8.git",
"cryptonote-util": "git://github.com/turtlecoin/node-cryptonote-util.git"
But that is not working with the pool of dvandal ... Hope he can implement that soon :-)
Thank you !!

**Comment by avense** [comment]
Bytecoin is also a forknote coin and I got it ....
https://bytecoin.pt

**Comment by Chinsusu** [comment]
I get this error in miner too.
PARSE error: Invalid target

**Comment by dvandal** [comment]
Hi,

Please upgrade to lastest release 1.3.2 and set "cnAlgorithm" to "cryptonight_light" and "cnVariant" to "1" for AEON v7 fork.

**Comment by leisegang** [comment]
This does not work for me.

**Comment by leisegang** [comment]
"cnAlgorithm": "cryptonight_light",
    "cnVariant": 1

**Comment by dvandal** [comment]
Lastest code and NPM packages updated ?

**Comment by delarius** [comment]
i try to update ... git pull ... npm update .. BUT

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/dvandal/node-cryptonight-hashing.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   Repository not found.
npm ERR! 
npm ERR! exited with error code: 128

**Comment by dvandal** [comment]
Please remove the package-lock.json file and retry npm update.

**Comment by leisegang** [comment]
I did the rm -RF node_modules
Then I did npm install

Gives me error on the block parsing.

**Comment by dvandal** [comment]
@leisegang Since turtle coin is a forknote, can you try using new cnBlobType setting to 1 or 2 ?

**Comment by delarius** [comment]
still have problems with turtlecoin.

Error: Failed to parse block
    at BlockTemplate.nextBlob (/home/trtlpool/pool/lib/pool.js:156:29)
    at Miner.getJob (/home/trtlpool/pool/lib/pool.js:335:41)
    at handleMinerMethod (/home/trtlpool/pool/lib/pool.js:469:28)
    at handleMessage (/home/trtlpool/pool/lib/pool.js:833:13)
    at Socket.<anonymous> (/home/trtlpool/pool/lib/pool.js:887:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by dvandal** [comment]
What are your pool cn algorithm, variant and blob type settings ?

**Comment by Chinsusu** [comment]
@dvandal  pls check with ipbc. I've done as CN_light, cnvariant 2, cnblob 0, it starts ok until there is a miner connects, the errors appear

**Comment by delarius** [comment]
At the moment I have tried just this for TurtleCoin:
    "cnAlgorithm": "cryptonight_light",
    "cnVariant": 1,


What should I add/change ?

**Comment by dvandal** [comment]
Turtle Coin is using " forknote ", you tried setting cnBlobType to 1 or 2 ?

**Comment by delarius** [comment]
ah .. it is working with cnBlobType = 2  !!!
Thank you !!!
