### ISSUE TITLE
npm update error unbuntu 18

### ISSUE THREAD

**Issue by Danniel0815** [dvandal/cryptonote-nodejs-pool#592]
does anyone know what this is a mistake?
npm update

```
make: Entering directory '/root/pool/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  COPY Release/bignum.node
make: Leaving directory '/root/pool/node_modules/bignum/build'

> cryptoforknote-util@7.0.2 install /root/pool/node_modules/cryptoforknote-util
> node-gyp rebuild

make: Entering directory '/root/pool/node_modules/cryptoforknote-util/build'
  CXX(target) Release/obj.target/cryptoforknote/src/main.o
clang: error: unknown argument: '-ftree-loop-if-convert-stores'
clang: error: unknown argument: '-fbranch-target-load-optimize2'
clang: warning: optimization flag '-fvariable-expansion-in-unroller' is not supported [-Wignored-optimization-argument]
cryptoforknote.target.mk:119: recipe for target 'Release/obj.target/cryptoforknote/src/main.o' failed
make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 1
make: Leaving directory '/root/pool/node_modules/cryptoforknote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.15.0-106-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/pool/node_modules/cryptoforknote-util
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@7.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptoforknote-util@7.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-13T17_55_39_792Z-debug.log
```

**Comment by muscleman** [comment]
node 10.20.1

**Comment by Danniel0815** [comment]
> node 10.20.1

sudo rm /pfad/node
sudo rm /pfad/nodejs
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt install -y nodejs
sudo reboot
