### ISSUE TITLE
node init.js failed ->  undefined symbol: node_module_register

### ISSUE THREAD

**Issue by xlp0rk0lx** [dvandal/cryptonote-nodejs-pool#6]
Running these command with a properly configuration file
npm update
node init.js
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/user/pool/cryptonote-nodejs-pool/node_modules/bignum/binding/bignum.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/user/pool/cryptonote-nodejs-pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
2018-03-07 12:37:56 [master] Pool fork 1 died, spawning replacement worker...

```
These are the node-modules installed 
```
async  base58-native  bignum  cli-color  cryptonote-util  dateformat  mailgun.js  multi-hashing  nodemailer  nodemailer-sendmail-transport  node-pre-gyp  redis
```

Unfortunatly i'm going into this issue.
node v4.8.7
npm v2.15.11

**Comment by dvandal** [comment]
The issue is with NPM version. To fix the issue you will need to remove NVM:
rm -rf $NVM_DIR ~/.npm ~/.bower
then reconnect to SSH

Once done you should see theses versions on ubuntu:

node v4.2.6
npm v3.5.2
