### ISSUE TITLE
Turtle coin pool

### ISSUE THREAD

**Issue by Ghost-ai-cpu** [dvandal/cryptonote-nodejs-pool#656]
Hi, How to setup pool for turtle coin with their latest [update](https://github.com/turtlecoin/turtlecoin/releases/tag/v1.0.0)

**Comment by masterprogrammer513** [comment]
Same here

**Comment by intensecoin** [comment]
Did you guys found the way to mine ?
I´m stuck on 👍 
2021-03-22 21:01:05 [daemon] intensecoin error from daemon
2021-03-22 21:01:06 [api] Error getting last block data {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}

**Comment by dagwood-Fenichuck** [comment]
Guys how did you sort this out please:  2021-03-22 21:01:06 [api] Error getting last block data {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}   Have same problem could you post the fix please

**Comment by maletazul** [comment]
@frandlyn26 

i try that, but return:

ReferenceError: fetch is not defined
    at getNetworkData (/home/luissilva/pool/lib/api.js:565:17)
    at network (/home/luissilva/pool/lib/api.js:379:4)
    at /home/luissilva/pool/node_modules/async/dist/async.js:3669:28
    at replenish (/home/luissilva/pool/node_modules/async/dist/async.js:446:21)
    at /home/luissilva/pool/node_modules/async/dist/async.js:451:13
    at eachOfLimit$1 (/home/luissilva/pool/node_modules/async/dist/async.js:477:34)
    at awaitable (/home/luissilva/pool/node_modules/async/dist/async.js:211:32)
    at eachOfGeneric (/home/luissilva/pool/node_modules/async/dist/async.js:512:16)
    at eachOf (/home/luissilva/pool/node_modules/async/dist/async.js:626:16)
    at awaitable (/home/luissilva/pool/node_modules/async/dist/async.js:211:32)
    at /home/luissilva/pool/node_modules/async/dist/async.js:3668:9
    at awaitable (/home/luissilva/pool/node_modules/async/dist/async.js:211:32)
    at Object.parallel (/home/luissilva/pool/node_modules/async/dist/async.js:3839:16)
    at collectStats (/home/luissilva/pool/lib/api.js:214:8)
    at Object.<anonymous> (/home/luissilva/pool/lib/api.js:2235:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/luissilva/pool/init.js:66:5)

**Comment by frandlyn26** [comment]
you need node-fetch module. https://stackoverflow.com/questions/48433783/referenceerror-fetch-is-not-defined
