### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by ayaseen** [dvandal/cryptonote-nodejs-pool#658]
I try different versions of nodejs (8/10/11) none of them worked with me by using this repo.

When I run nodejs init.js,  I got this error:

 node init.js -config=kva.json
2021-02-20 21:19:45 [master] Starting Cryptonote Node.JS pool version v2.0.0
2021-02-20 21:19:45 [master] Developer donation (devDonation) is set to 0.1%, Please consider raising it to 0.2% or higher !!!
2021-02-20 21:19:45 [master] Pool spawned on 4 thread(s)
/root/pool/lib/utils.js:27
var addressBase58Prefix = config.poolServer.pubAddressPrefix ? parseInt(config.poolServer.pubAddressPrefix) : parseInt(cnUtil.address_decode(Buffer.from(config.poolServer.poolAddress)).toString());
                                                                                                                                                                                        ^

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/root/pool/lib/utils.js:27:185)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/pool/lib/daemon.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
2021-02-20 21:19:46 [master] Daemon died, spawning replacement...

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/root/pool/lib/utils.js:27:185)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/pool/lib/notifications.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/pool/lib/pool.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

What is this means?

By the way, I try another repo with nodejs version 8, and somehow it worked.

Any idea, what I have missed here?

**Comment by mahdiamer** [comment]
Good

**Comment by dvandal** [comment]
You pool wallet address is wrong in JSON config file.

**Comment by ayaseen** [comment]
@dvandal 
I am trying to run against Kevacoin. It seems is not supported right now.
Would you please do support Kevacoin.

Thanks

**Comment by thefundcrypto** [comment]
Hello, checking to see if there is any traction on this? I see other projects running kevacoin, so I assuming KVA is supported, but just has a different config.
With Keva I have the following
    "daemon": {
        "host": "127.0.0.1",
        "port": 19332,
        "user": "xxxxxx",
        "password": "xxxxxxxxx"
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 19332
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null
    },
    These are the default ports and config from their node-js site... Something seems to be missing because I am getting the same error.
