### ISSUE TITLE
Haven and blocks.map is not a function

### ISSUE THREAD

**Issue by joescalon** [dvandal/cryptonote-nodejs-pool#678]
I run a pool and every since new dvandal update blocks can be found but blockunlocker is constantly crashing. It doesn't orphan a block but does not pay out. The logged error I get is below.
TypeError: blocks.map is not a function
    at /home/server/pool/lib/blockUnlocker.js:120:31
    at nextTask (/home/server/pool/node_modules/async/dist/async.js:4576:27)
    at next (/home/server/pool/node_modules/async/dist/async.js:4584:13)
    .................

This issue is posted previously without any real fix. I tested with Node 12 and Node 14 both same issue. Does anyone have a fix for this or at least the old dvandal code. Thanks.

**Comment by xtc18** [comment]
> I run a pool and every since new dvandal update blocks can be found but blockunlocker is constantly crashing. It doesn't orphan a block but does not pay out. The logged error I get is below.
> TypeError: blocks.map is not a function
> at /home/server/pool/lib/blockUnlocker.js:120:31
> at nextTask (/home/server/pool/node_modules/async/dist/async.js:4576:27)
> at next (/home/server/pool/node_modules/async/dist/async.js:4584:13)
> .................
> 
> This issue is posted previously without any real fix. I tested with Node 12 and Node 14 both same issue. Does anyone have a fix for this or at least the old dvandal code. Thanks.

Use async version 1.5.2 to resolve this.

**Comment by insidenothing** [comment]
Thank you, npm install async@1.5.2 fixed the issue for me
