### ISSUE TITLE
Spamming errors while trying to start.

### ISSUE THREAD

**Issue by XfedeX** [dvandal/cryptonote-nodejs-pool#679]
This is log:
```
fede@FedeVM:~/pool$ node init.js

[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mPool spawned on 1 thread(s)
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0

Error: Could not locate the bindings file. Tried:
 → /home/fede/pool/node_modules/cryptoforknote-util/build/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/default/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/compiled/14.17.0/linux/x64/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/release/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/debug/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/default/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/lib/binding/node-v83-linux-x64/cryptoforknote.node
    at bindings (/home/fede/pool/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/fede/pool/node_modules/cryptoforknote-util/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fede/pool/lib/utils.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)


Error: Cannot find module 'bignum'
Require stack:
- /home/fede/pool/lib/pool.js
- /home/fede/pool/init.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fede/pool/lib/pool.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)

[34m2021-06-14 18:03:22[39m[1m[37m [chartsDataCollector] [39m[22mStarted
[31m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mDaemon died, spawning replacement...
[31m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mPool fork 1 died, spawning replacement worker...
[34m2021-06-14 18:03:22[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0

Error: Could not locate the bindings file. Tried:
 → /home/fede/pool/node_modules/cryptoforknote-util/build/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/default/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/compiled/14.17.0/linux/x64/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/release/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/debug/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/default/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/lib/binding/node-v83-linux-x64/cryptoforknote.node
    at bindings (/home/fede/pool/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/fede/pool/node_modules/cryptoforknote-util/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fede/pool/lib/utils.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)

[31m2021-06-14 18:03:23[39m[1m[37m [master] [39m[22mDaemon died, spawning replacement...
[34m2021-06-14 18:03:23[39m[1m[37m [master] [39m[22mStarting Cryptonote Node.JS pool version v2.0.0

Error: Could not locate the bindings file. Tried:
 → /home/fede/pool/node_modules/cryptoforknote-util/build/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/default/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/compiled/14.17.0/linux/x64/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/release/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/debug/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/default/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/lib/binding/node-v83-linux-x64/cryptoforknote.node
    at bindings (/home/fede/pool/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/fede/pool/node_modules/cryptoforknote-util/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fede/pool/lib/utils.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)


Error: Could not locate the bindings file. Tried:
 → /home/fede/pool/node_modules/cryptoforknote-util/build/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Debug/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/out/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/Release/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/build/default/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/compiled/14.17.0/linux/x64/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/release/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/debug/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/addon-build/default/install-root/cryptoforknote.node
 → /home/fede/pool/node_modules/cryptoforknote-util/lib/binding/node-v83-linux-x64/cryptoforknote.node
    at bindings (/home/fede/pool/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/fede/pool/node_modules/cryptoforknote-util/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fede/pool/lib/utils.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fede/pool/lib/notifications.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)`
```

And if I try to do npm install cryptoforknote-util i get error:
fede@FedeVM:~$ npm install cryptoforknote-util
```
> cryptoforknote-util@7.0.2 install /home/fede/node_modules/cryptoforknote-util
> node-gyp rebuild

make: Entering directory '/home/fede/node_modules/cryptoforknote-util/build'
  CXX(target) Release/obj.target/cryptoforknote/src/main.o
make: g++: Command not found
make: *** [cryptoforknote.target.mk:130: Release/obj.target/cryptoforknote/src/main.o] Error 127
make: Leaving directory '/home/fede/node_modules/cryptoforknote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-55-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fede/node_modules/cryptoforknote-util
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/fede/package.json'
npm WARN fede No description
npm WARN fede No repository field.
npm WARN fede No README data
npm WARN fede No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@7.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptoforknote-util@7.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fede/.npm/_logs/2021-06-14T16_06_05_958Z-debug.log
```
If this is relevant, i wasn't able to do `echo 1024 > /proc/sys/net/core/somaxconn` even under sudo, because of
`bash: /proc/sys/net/core/somaxconn: Permission denied`
Running Ubuntu on a VirtualBox VPS (i run the VPS on my Windows 10 home machine)

**Comment by trasherdk** [comment]
This `make: g++: Command not found` should give you a hint :smiley:
