### ISSUE TITLE
node init.js

### ISSUE THREAD

**Issue by Sarahshohani** [dvandal/cryptonote-nodejs-pool#692]
I have get this error while performing node init.js
could you please help?
uname -a:
Linux vmi677535.contaboserver.net 4.15.0-134-generic #138-Ubuntu SMP Fri Jan 15 10:52:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I have installed node 11 ,14,16 but none of them worked I have also tried nvm but didn't worked for me.

/root/pool/node_modules/dateformat/lib/dateformat.js:1
var token=/d{1,4}|D{3,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|W{1,2}|[LlopSZN]|"[^"]*"|'[^']*'/g;var timezone=/\b(?:[A-Z]{1,3}[A-Z][TC])(?:[-+]\d{4})?|((?:Australian )?(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time)\b/g;var timezoneClip=/[^-+\dA-Z]/g;export default function dateFormat(date,mask,utc,gmt){if(arguments.length===1&&typeof date==="string"&&!/\d/.test(date)){mask=date;date=undefined}date=date||date===0?date:new Date;if(!(date instanceof Date)){date=new Date(date)}if(isNaN(date)){throw TypeError("Invalid date")}mask=String(masks[mask]||mask||masks["default"]);var maskSlice=mask.slice(0,4);if(maskSlice==="UTC:"||maskSlice==="GMT:"){mask=mask.slice(4);utc=true;if(maskSlice==="GMT:"){gmt=true}}var _=function _(){return utc?"getUTC":"get"};var _d=function d(){return date[_()+"Date"]()};var D=function D(){return date[_()+"Day"]()};var _m=function m(){return date[_()+"Month"]()};var y=function y(){return date[_()+"Full

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/root/pool/lib/logger.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)

**Comment by Stardock2018** [comment]
Graft.westcoastxmr.ca

**Comment by Stardock2018** [comment]
What Ubuntu version are you using?

**Comment by dagwood-Fenichuck** [comment]
ubuntu 18.04 bionic

**Comment by dagwood-Fenichuck** [comment]
Installed everything in package.json   plus two peer dependencies build says were missing,  do you have a screenshot of the console running the pool at the end when you node init.js

**Comment by maletazul** [comment]
> Yes if you can i can't get the miner connection to start

Like me

**Comment by dagwood-Fenichuck** [comment]
Thank you guys  now running.  have turtlecoin node in /home/user/  and pool in /var/www/pool   can't connect to node daemon with pool on 127.0.0.1 or 0.0.0.0   have used my  domain.com  using nginx with reverse proxy. you can see its working.
error from daemon
2021-11-11 02:15:34 [api] Error getting last block data {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
2021-11-11 02:15:34 [api] Stat collection finished: 1 ms redis, 25 ms daemon

API started & listening on 0.0.0.0 port 8117
2021-11-11 02:15:09 [pool] (Thread 1) Clear values for connected workers in redis database.
(node:15224) ExperimentalWarning: queueMicrotask() is experimental.
2021-11-11 02:15:09 [pool] (Thread 3) Clear values for port 3333 in redis database.
2021-11-11 02:15:09 [pool] (Thread 3) Started server listening on port 3333
2021-11-11 02:15:09 [pool] (Thread 3) Clear values for port 4444 in redis database.
2021-11-11 02:15:09 [pool] (Thread 3) Started server listening on port 4444
2021-11-11 02:15:09 [pool] (Thread 3) Clear values for port 5555 in redis database.
2021-11-11 02:15:09 [pool] (Thread 3) Started server listening on port 5555

So it's not connecting to daemon  someone tell me how to connect to this turtlecoin daemon please

**Comment by 88plug** [comment]
> Had the same issue yesterday. Found out the npm dateformat package has some recent updates that results in the above error. For me, changing the `"dateformat": "*"` to `"dateformat": "4.5.1"` in `package.json`, and run `npm update` again, fixed the issue.

Works to solve the original error!

**Comment by domajor** [comment]
:~/pool$ node init.js
2023-10-06 22:08:09 [master] Starting Cryptonote Node.JS pool version v2.0.0
(node:10999) UnhandledPromiseRejectionWarning: Error: The client is closed
ubuntu 20
