### ISSUE TITLE
Fatal on start due to mailgun file

### ISSUE THREAD

**Issue by cbarraford** [dvandal/cryptonote-nodejs-pool#7]
I just git pulled the latest and did a `npm update` and ran `node init.js` and got the following error. I'm running `v0.10.48` of node. Any thoughts?

```
/srv/cryptonote-nodejs-pool/node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/cryptonote-nodejs-pool/node_modules/mailgun.js/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by cbarraford** [comment]
same issue as https://github.com/sumoprojects/cryptonote-sumokoin-pool/issues/22

**Comment by dvandal** [comment]
The code require node.js version 4.x or later, you will need to upgrade the currently running release to fix this error

**Comment by cbarraford** [comment]
👍

**Comment by meatworksnc** [comment]
I still have the same issue even with updated verision of node 0.10.30

Linux Centos 7

let me know..

**Comment by etnminers** [comment]
Here the same error with all the updates I could think of:
/root/pool/node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^
SyntaxError: Unexpected reserved word

apt-get install -y nodejs
nodejs is already the newest version (8.11.2-1nodesource1).
node -v
v0.10.48
I have the same error. Ubuntu 16.04.
