### ISSUE TITLE
turtlecoin Payments error

### ISSUE THREAD

**Issue by maletazul** [dvandal/cryptonote-nodejs-pool#705]
Hi all,

anyone expirience this error in a turtlecoin pool?

TypeError: Cannot read property 'transactionHash' of undefined
    at /home/ubuntu/atcpool/lib/paymentProcessor.js:246:54
    at /home/ubuntu/atcpool/lib/apiInterfaces.js:66:3
    at IncomingMessage.<anonymous> (/home/ubuntu/atcpool/lib/apiInterfaces.js:41:5)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

**Comment by muscleman** [comment]
how can pool be working, turtlecoin uses api requests not rpc
