### ISSUE TITLE
There is a "Repository not found" error when running "npm update"

### ISSUE THREAD

**Issue by jasonfifa** [dvandal/cryptonote-nodejs-pool#714]
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/turtlecoin/node8-multi-hashing.git
npm ERR! 
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.

**Comment by Cideg** [comment]
just find the connection.

just use a different template.

git+https://github.com/jowy81/node8-multi-hashing
or https://github.com/BlackPeter13/node8-multihashing
or https://github.com/search?o=desc&q=node8-multi-hashing&s=&type=Code

**Comment by Cideg** [comment]
´``{
	"name": "cryptonote-nodejs-pool",
	"version": "1.4.0",
	"license": "GPL-2.0",
	"Original author": "Daniel Vandal",
	"Maintained by": "Musclesonvacation",
	"repository": {
		"type": "git",
		"url": "https://github.com/dvandal/cryptonote-nodejs-pool.git"
	},
	"dependencies": {
		"async": "^3.2.0",
		"base58-native": "*",
		"bignum": "*",
		"bufferutil": "*",
		"cli-color": "*",
		"cryptoforknote-util": "git+https://github.com/MoneroOcean/node-cryptoforknote-util.git",
		"cryptonight-hashing": "git+https://github.com/MoneroOcean/node-cryptonight-hashing.git",
		"dateformat": "3.0.3",
		"domexception": "*",
		"mailgun.js": "*",
		"node-telegram-bot-api": "*",
		"nodemailer": "^6.4.18",
		"nodemailer-sendmail-transport": "*",
		"redis": "*",
		"socket.io": "^3.1.1",
		"time-ago": "*",
		"turtlecoin-multi-hashing": "git+https://github.com/BlackPeter13/node8-multihashing.git",
		"utf-8-validate": "*"
	},
	"engines": {
		"node": ">=8.11.3"
	}
}```

**Comment by Cideg** [comment]
that depends on which one you want to use and on which system.

for starters try version 11, otherwise higher


curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash
sudo apt-get install -y nodejs
npm update

or
https://github.com/Cideg/cryptonote-nodejs-pool/commit/858efc2d4a623900c9db5f357736f412111f6a0b
--version v11.15.0

nvm install v11.15.0
nvm use v11.15.0

**Comment by jasonfifa** [comment]
Still having error when runing "npm updte" using ubuntu 18 and nvm v11.15.0.

../boolberry.cc:2:10: fatal error: crypto/cryptonote_core/cryptonote_format_utils.h: No such file or directory
 #include "crypto/cryptonote_core/cryptonote_format_utils.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
multihashing.target.mk:177: recipe for target 'Release/obj.target/multihashing/boolberry.o' failed
make: *** [Release/obj.target/multihashing/boolberry.o] Error 1
make: Leaving directory '/home/jc/pool/node_modules/turtlecoin-multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.15.0-196-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jc/pool/node_modules/turtlecoin-multi-hashing
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! turtlecoin-multi-hashing@0.0.19 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the turtlecoin-multi-hashing@0.0.19 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jasonfifa** [comment]
I just ran "npm update" successfully after using the "github.com/jowy81/node8-multi-hashing" instead of "github.com/BlackPeter13/node8-multihashing".   
Thanks!

There are 3 high severity vulnerabilities after running the "npm update". Can I just ignore it at the moment?

***************************************************************************
+ cryptoforknote-util@12.0.0
+ turtlecoin-multi-hashing@0.0.19
+ cryptonight-hashing@28.0.7
updated 3 packages and audited 210 packages in 69.45s
found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
jc@jc-161:~/pool$ 
***************************************************************************

**Comment by BreadJS** [comment]
> Still having error when runing "npm updte" using ubuntu 18 and nvm v11.15.0.
> 
> ../boolberry.cc:2:10: fatal error: crypto/cryptonote_core/cryptonote_format_utils.h: No such file or directory #include "crypto/cryptonote_core/cryptonote_format_utils.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. multihashing.target.mk:177: recipe for target 'Release/obj.target/multihashing/boolberry.o' failed make: *** [Release/obj.target/multihashing/boolberry.o] Error 1 make: Leaving directory '/home/jc/pool/node_modules/turtlecoin-multi-hashing/build' gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23) gyp ERR! stack at ChildProcess.emit (events.js:193:13) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12) gyp ERR! System Linux 4.15.0-196-generic gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /home/jc/pool/node_modules/turtlecoin-multi-hashing gyp ERR! node -v v11.15.0 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! turtlecoin-multi-hashing@0.0.19 install: `node-gyp rebuild` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the turtlecoin-multi-hashing@0.0.19 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Use node v12

**Comment by haov000** [comment]
"turtlecoin-multi-hashing": "git+https://github.com/benrod3k/node8-multi-hashing.git",
it's ok
