### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by muhamadridwanid** [dvandal/cryptonote-nodejs-pool#80]
Plese help, i'm using masari.

Error: Failed to parse block
    at Error (native)
    at Object.BlockTemplate.nextBlob (/root/pool2/lib/pool.js:155:29)
    at Object.Miner.getJob (/root/pool2/lib/pool.js:331:41)
    at handleMinerMethod (/root/pool2/lib/pool.js:465:28)
    at handleMessage (/root/pool2/lib/pool.js:832:13)
    at Socket.<anonymous> (/root/pool2/lib/pool.js:886:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)

2018-05-06 17:53:29 [master] Pool fork 1 died, spawning replacement worker...

**Comment by Invisys** [comment]
Masari requires non-standard cryptonote-util.
Change in package.json:
"cryptonote-util": "git://github.com/dvandal/node-cryptonote-util",
to
"cryptonote-util": "git://github.com/masari-project/node-cryptonote-util#msr",

**Comment by muhamadridwanid** [comment]
it's working like a charm 👍 
thanks
