### ISSUE TITLE
Iridium Coin failed to parse block

### ISSUE THREAD

**Issue by jvmatamu** [dvandal/cryptonote-nodejs-pool#86]
When try connect miner to pool got this log, 

`Error: Failed to parse block
    at BlockTemplate.nextBlob (/root/pool/lib/pool.js:154:29)
    at Miner.getJob (/root/pool/lib/pool.js:330:41)
    at handleMinerMethod (/root/pool/lib/pool.js:464:28)
    at handleMessage (/root/pool/lib/pool.js:828:13)
    at Socket.<anonymous> (/root/pool/lib/pool.js:882:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

2018-05-08 06:11:26 [master] Pool fork 1 died, spawning replacement worker...
2018-05-08 06:11:28 [pool] (Thread 1) Invalid cryptonight algorithm: cryptonight_light
2018-05-08 06:11:28 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603
2018-05-08 06:11:28 [pool] (Thread 1) Clear values for connected workers in redis database.
2018-05-08 06:11:28 [pool] (Thread 1) Clear values for port 3333 in redis database.
2018-05-08 06:11:28 [pool] (Thread 1) Started server listening on port 3333
2018-05-08 06:11:28 [pool] (Thread 1) Clear values for port 4444 in redis database.
2018-05-08 06:11:28 [pool] (Thread 1) Started server listening on port 4444
2018-05-08 06:11:28 [pool] (Thread 1) Clear values for port 5555 in redis database.
2018-05-08 06:11:28 [pool] (Thread 1) Started server listening on port 5555
2018-05-08 06:11:28 [pool] (Thread 1) Clear values for port 7777 in redis database.
2018-05-08 06:11:28 [pool] (Thread 1) Started server listening on port 7777
2018-05-08 06:11:29 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603
2018-05-08 06:11:30 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603
2018-05-08 06:11:31 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603
2018-05-08 06:11:32 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603
2018-05-08 06:11:33 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603
2018-05-08 06:11:34 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603
2018-05-08 06:11:35 [pool] (Thread 1) New block to mine at height 118619 w/ difficulty of 154425603`

check on official github on package.json with this.
        "multi-hashing": "https://github.com/iridiumdev/node8-multi-hashing.git",
        "cryptonote-util": "https://github.com/iridiumdev/node-cryptonote-util.git"

Thanks

**Comment by dvandal** [comment]
Iridium is using Cryptonight Light variant 1, using lastest code set your config like this: "cnAlgorithm" to "cryptonight_light" and "cnVariant" to "1"

**Comment by PsychoSterope** [comment]
So I am attempting to run a new VM using 1.3.2 and I am getting the same exact error with Masari. I did some digging and I see that in verison 1.3.2 pool.js there is a line that wasn't in 1.3.1.
Line 15 var cnHashing = require('cryptonight-hashing');

I bring this up because with 1.3.1 I still have to use:
"cnAlgorithm": "cryptonight",
    "cnVariant": 1,
And the current live pool is running just fine (minus some mailgun, telegram and stats issues)

The only other variations I have from the live pool and the test VM are nodejs  4.x vs 8.x and I can't use the masari cryptonote-util in the package.json as it fails to pass the npm update ( I get a npm-gyp fail).

I am able to load the webpages, and the pool is running, but as soon as I try to connect a miner to the test pool, it dies with the errors listed above and in two other issues threads.

**Comment by jvmatamu** [comment]
@dvandal  how to convert this prefix to number ?
uint64_t const CRYPTONOTE_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX = 0x6599

**Comment by dvandal** [comment]
All issues fixed now. Please try theses settings:

    "coin": "iridium",
    "symbol": "IRD",
    "coinUnits": 100000000,
    "coinDifficultyTarget": 175,
    "cnAlgorithm": "cryptonight_light",
    "cnVariant": 1,
    "cnBlobType": 2,
