### ISSUE TITLE
Masari - Pool errors

### ISSUE THREAD

**Issue by hypeboard** [dvandal/cryptonote-nodejs-pool#94]
after you recent update I am having a very hard time getting the pool working
-------------------------

/pool$ node init.js
2018-05-09 07:34:29 [master] Starting Cryptonote Node.JS pool version v1.3.2
2018-05-09 07:34:29 [master] Pool spawned on 1 thread(s)
2018-05-09 07:34:30 [chartsDataCollector] Started
2018-05-09 07:34:31 [payments] Started
2018-05-09 07:34:31 [unlocker] Started
2018-05-09 07:34:31 [unlocker] No blocks candidates in redis
2018-05-09 07:34:31 [payments] No workers' balances reached the minimum payment threshold
2018-05-09 07:34:31 [pool] (Thread 1) Error polling getblocktemplate {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
2018-05-09 07:34:31 [pool] (Thread 1) Could not start pool
2018-05-09 07:34:32 [pool] (Thread 1) Error polling getblocktemplate {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
2018-05-09 07:34:32 [pool] (Thread 1) Could not start pool
2018-05-09 07:34:33 [pool] (Thread 1) Error polling getblocktemplate {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
2018-05-09 07:34:33 [pool] (Thread 1) Could not start pool
2018-05-09 07:34:34 [pool] (Thread 1) Error polling getblocktemplate {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
2018-05-09 07:34:34 [pool] (Thread 1) Could not start pool
2018-05-09 07:34:35 [pool] (Thread 1) Error polling getblocktemplate {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
2018-05-09 07:34:35 [pool] (Thread 1) Could not start pool
2018-05-09 07:34:36 [pool] (Thread 1) Error polling getblocktemplate {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
2018-05-09 07:34:36 [pool] (Thread 1) Could not start pool
2018-05-09 07:34:37 [pool] (Thread 1) Error polling getblocktemplate {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}

----------------------------------------

I saw in a closed issue you said that         "cryptonote-util": "git://github.com/masari-project/node-cryptonote-util#msr", needed to be in the package.json which I added though it did not help me

{
    "name": "cryptonote-nodejs-pool",
    "version": "1.3.2",
    "license": "GPL-2.0",
    "author": "Daniel Vandal",
    "repository": {
        "type": "git",
        "url": "https://github.com/dvandal/cryptonote-nodejs-pool.git"
    },
    "dependencies": {
        "bignum": "*",
        "async": "1",
        "redis": "*",
        "cli-color": "*",
        "dateformat": "*",
        "time-ago": "*",
        "base58-native": "*",
        "socket.io": "*",
        "nodemailer": "2.7.2",
        "nodemailer-sendmail-transport": "*",
        "mailgun.js": "*",
        "node-telegram-bot-api": "*",
        "cryptonote-util": "git://github.com/masari-project/node-cryptonote-util#msr",
        "cryptoforknote-util": "git://github.com/MoneroOcean/node-cryptoforknote-util",
        "cryptonight-hashing": "git://github.com/MoneroOcean/node-cryptonight-hashing"
    },
    "engines": {
        "node": ">=4.0"
    }
}

where have I gone wrong?

**Comment by Zpay-Network** [comment]
check your daemon port and wallet port

**Comment by hypeboard** [comment]
ok I am a dummy... That was the problem but a new problem has arisen. I can get the pool to start correctly but as soon as I connect a miner to it it dies.. Errors are below. 
--------------------------------------------
~/pool$ node init.js
2018-05-09 14:35:33 [master] Starting Cryptonote Node.JS pool version v1.3.2
2018-05-09 14:35:33 [master] Pool spawned on 1 thread(s)
2018-05-09 14:35:34 [chartsDataCollector] Started
2018-05-09 14:35:34 [payments] Started
2018-05-09 14:35:34 [unlocker] Started
2018-05-09 14:35:34 [unlocker] No blocks candidates in redis
2018-05-09 14:35:34 [payments] No workers' balances reached the minimum payment
2018-05-09 14:35:34 [pool] (Thread 1) New block to mine at height 175535 w/ diff
2018-05-09 14:35:34 [pool] (Thread 1) Clear values for connected workers in redi
2018-05-09 14:35:34 [pool] (Thread 1) Clear values for port 3333 in redis databa
2018-05-09 14:35:34 [pool] (Thread 1) Started server listening on port 3333
2018-05-09 14:35:34 [pool] (Thread 1) Clear values for port 4444 in redis databa
2018-05-09 14:35:34 [pool] (Thread 1) Started server listening on port 4444
2018-05-09 14:35:34 [pool] (Thread 1) Clear values for port 5555 in redis databa
2018-05-09 14:35:34 [pool] (Thread 1) Started server listening on port 5555
2018-05-09 14:35:34 [pool] (Thread 1) Clear values for port 7777 in redis databa
2018-05-09 14:35:34 [pool] (Thread 1) Started server listening on port 7777
2018-05-09 14:35:34 [pool] (Thread 1) Clear values for port 8888 in redis databa
2018-05-09 14:35:34 [pool] (Thread 1) Started server listening on port 8888
2018-05-09 14:35:34 [pool] (Thread 1) Clear values for port 9999 in redis databa
2018-05-09 14:35:34 [pool] (Thread 1) Started server listening on port 9999
2018-05-09 14:35:35 [pool] (Thread 1) New block to mine at height 175536 w/ diff

Error: Failed to parse block
    at BlockTemplate.nextBlob (/home/hyperionx/pool/lib/pool.js:154:29)
    at Miner.getJob (/home/hyperionx/pool/lib/pool.js:330:41)
    at handleMinerMethod (/home/hyperionx/pool/lib/pool.js:464:28)
    at handleMessage (/home/hyperionx/pool/lib/pool.js:828:13)
    at Socket.<anonymous> (/home/hyperionx/pool/lib/pool.js:882:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)


Error: Failed to parse block
    at BlockTemplate.nextBlob (/home/hyperionx/pool/lib/pool.js:154:29)
    at Miner.getJob (/home/hyperionx/pool/lib/pool.js:330:41)
    at handleMinerMethod (/home/hyperionx/pool/lib/pool.js:464:28)
    at handleMessage (/home/hyperionx/pool/lib/pool.js:828:13)
    at Socket.<anonymous> (/home/hyperionx/pool/lib/pool.js:882:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)


Error: Failed to parse block
    at BlockTemplate.nextBlob (/home/hyperionx/pool/lib/pool.js:154:29)
    at Miner.getJob (/home/hyperionx/pool/lib/pool.js:330:41)
    at handleMinerMethod (/home/hyperionx/pool/lib/pool.js:464:28)
    at handleMessage (/home/hyperionx/pool/lib/pool.js:828:13)
    at Socket.<anonymous> (/home/hyperionx/pool/lib/pool.js:882:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)


Error: Failed to parse block
    at BlockTemplate.nextBlob (/home/hyperionx/pool/lib/pool.js:154:29)
    at Miner.getJob (/home/hyperionx/pool/lib/pool.js:330:41)
    at handleMinerMethod (/home/hyperionx/pool/lib/pool.js:464:28)
    at handleMessage (/home/hyperionx/pool/lib/pool.js:828:13)
    at Socket.<anonymous> (/home/hyperionx/pool/lib/pool.js:882:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

2018-05-09 14:35:56 [master] Pool fork 1 died, spawning replacement worker...
2018-05-09 14:35:59 [pool] (Thread 1) New block to mine at height 175536 w/ diff
2018-05-09 14:35:59 [pool] (Thread 1) Clear values for connected workers in redi
2018-05-09 14:35:59 [pool] (Thread 1) Clear values for port 3333 in redis databa
2018-05-09 14:35:59 [pool] (Thread 1) Started server listening on port 3333
2018-05-09 14:35:59 [pool] (Thread 1) Clear values for port 4444 in redis databa
2018-05-09 14:35:59 [pool] (Thread 1) Started server listening on port 4444
2018-05-09 14:35:59 [pool] (Thread 1) Clear values for port 5555 in redis databa
2018-05-09 14:35:59 [pool] (Thread 1) Started server listening on port 5555
2018-05-09 14:35:59 [pool] (Thread 1) Clear values for port 7777 in redis databa
2018-05-09 14:35:59 [pool] (Thread 1) Started server listening on port 7777
2018-05-09 14:35:59 [pool] (Thread 1) Clear values for port 8888 in redis databa
2018-05-09 14:35:59 [pool] (Thread 1) Started server listening on port 8888
2018-05-09 14:35:59 [pool] (Thread 1) Clear values for port 9999 in redis databa
2018-05-09 14:35:59 [pool] (Thread 1) Started server listening on port 9999
^C

**Comment by hypeboard** [comment]
That fixed everything!!! Thank you. If no one has told you, You are awesome!! Your fast response time and fixes are above and beyond. Thank you again!!!!

**Comment by dvandal** [comment]
Thanks for your comments, I appreciate :)
