### ISSUE TITLE
Worker Statistics Error for miner use address with payment id

### ISSUE THREAD

**Issue by Zpay-Network** [dvandal/cryptonote-nodejs-pool#95]
hi i found error in miner statistics
when you try to use the payment id will appear statistics and then lost

**Comment by Chinsusu** [comment]
I get the same issue

**Comment by dvandal** [comment]
Ok, I fixed the issue bad delimiter in redis database, previous statistics will not be available but will be fixed for new statistics data.

**Comment by Chinsusu** [comment]
just with payment id, the integrated wallet works perfect

**Comment by dvandal** [comment]
Please try with lastest code.

**Comment by Zpay-Network** [comment]
hi, this work for latest code, thanks
but I found a new problem

each mining using the wrong address pool gets an error message
`TypeError: Cannot read property 'toString' of undefined
    at getAddressPrefix (/root/pool/lib/utils.js:30:70)
    at Object.exports.validateMinerAddress (/root/pool/lib/utils.js:38:25)
    at handleMinerMethod (/root/pool/lib/pool.js:461:24)
    at handleMessage (/root/pool/lib/pool.js:838:13)
    at Socket.<anonymous> (/root/pool/lib/pool.js:892:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)


TypeError: Cannot read property 'toString' of undefined
    at getAddressPrefix (/root/pool/lib/utils.js:30:70)
    at Object.exports.validateMinerAddress (/root/pool/lib/utils.js:38:25)
    at handleMinerMethod (/root/pool/lib/pool.js:461:24)
    at handleMessage (/root/pool/lib/pool.js:838:13)
    at Socket.<anonymous> (/root/pool/lib/pool.js:892:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)


TypeError: Cannot read property 'toString' of undefined
    at getAddressPrefix (/root/pool/lib/utils.js:30:70)
    at Object.exports.validateMinerAddress (/root/pool/lib/utils.js:38:25)
    at handleMinerMethod (/root/pool/lib/pool.js:461:24)
    at handleMessage (/root/pool/lib/pool.js:838:13)
    at Socket.<anonymous> (/root/pool/lib/pool.js:892:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)


TypeError: Cannot read property 'toString' of undefined
    at getAddressPrefix (/root/pool/lib/utils.js:30:70)
    at Object.exports.validateMinerAddress (/root/pool/lib/utils.js:38:25)
    at handleMinerMethod (/root/pool/lib/pool.js:461:24)
    at handleMessage (/root/pool/lib/pool.js:838:13)
    at Socket.<anonymous> (/root/pool/lib/pool.js:892:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

2018-05-11 16:02:37 [master] Pool fork 1 died, spawning replacement worker...
`
and all connected miners will be disconnected

**Comment by dvandal** [comment]
Fixed in lastest code.

**Comment by Zpay-Network** [comment]
yeah thanks, perfect now :+1: 
hmm
i just start mine with latest code for 1 hour, and no chart show up?
how long the chart will be showing?

**Comment by dvandal** [comment]
Thanks, just fixed the miners hashrate chart issue.
